#!/usr/bin/env bash

# Install the semantic_version package
pip install -t ${ZOE_HOME}/lib/python semantic_version

# Create additional directories
mkdir ${ZOE_HOME}/etc/zam
mkdir ${ZOE_HOME}/etc/zam/info

# Create the agent list
echo "[zam]
source = https://github.com/rmed/zoe_agent_manager.git
installed = 1
version = 0.7.4" > ${ZOE_HOME}/etc/zam/list

# Create file list (used for updates)
echo "agents/zam/zam.py
cmdproc/zam.pl" > ${ZOE_HOME}/etc/zam/info/zam.list
